spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/PetBnB
spring.datasource.username=${POSTGRES_USER:petbnbuser}
spring.datasource.password=${POSTGRES_PASSWORD:petpet}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
